# Generated by Django 3.2.13 on 2023-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('cinema_release_date', models.DateField()),
                ('full_path', models.CharField(max_length=255)),
                ('full_paths', models.JSONField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('jw_entity_id', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('poster_blur_hash', models.CharField(max_length=255)),
                ('scoring', models.JSONField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
