# Generated by Django 3.2.12 on 2023-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='tmdb',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
