# Generated by Django 3.2.12 on 2023-05-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ott',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
