# Generated by Django 3.2.12 on 2023-05-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230522_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='image',
        ),
    ]
