# Generated by Django 3.2.12 on 2023-05-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_ott_image'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myOtt',
            field=models.ManyToManyField(blank=True, to='movies.Ott'),
        ),
    ]
