# Generated by Django 3.2.12 on 2023-05-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_myott'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='myOtt',
            new_name='ott_user',
        ),
    ]
