# Generated by Django 3.2.12 on 2023-05-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_myott_user_ott_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ott_user',
        ),
    ]
