# Generated by Django 3.2.12 on 2023-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already', models.JSONField(blank=True, null=True)),
                ('prefer', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
