# Generated by Django 3.2.13 on 2023-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.CharField(max_length=200)),
                ('full_paths', models.JSONField(default=dict)),
                ('jw_entity_id', models.CharField(max_length=20)),
                ('object_type', models.CharField(max_length=20)),
                ('poster', models.CharField(max_length=200)),
                ('poster_blur_hash', models.CharField(max_length=100)),
                ('scoring', models.JSONField()),
                ('title', models.CharField(max_length=100)),
                ('tmdb_id', models.IntegerField(null=True)),
            ],
        ),
    ]
